WebIT/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, re_path

from python_test.views import MainPage, AddClient, SearchClient, ShowClientDetails, ModifyClient, DeleteClient

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', MainPage.as_view(), name="home"),
    re_path(r'^add/', AddClient.as_view(), name="add"),
    re_path(r'^search/', SearchClient.as_view(), name="search"),
    re_path(r'^delete/(?P<id>[0-9]+)$', DeleteClient.as_view(), name="delete"),
    re_path(r'^modify/(?P<id>[0-9]+)$', ModifyClient.as_view(), name = "modify"),
re_path(r'^details/(?P<id>[0-9]+)$', ShowClientDetails.as_view(), name = "ClientDetails"),

]

python_test/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MaxValueValidator

AU_STATES = (
    (1, "New South Wales"),
    (2, "Victoria"),
    (3, "Queensland"),
    (4, "Western Australia"),
    (5, "South Australia"),
    (6, "Tasmania"),
    (7, "Australian Capital Territory"),
    (8, "Northern Territory"),
    (9, "Norfolk Island"),
    (10, "Christmas Island"),
    (11, "Australian Antarctic Territory"),
    (12, "Cocos (Keeling) Islands"),
    (13, "Jervis Bay Territory"),
    (14, "Coral Sea Islands"),
    (15, "Ashmore and Cartier Islands"),
    (16, "Heard Island and McDonald Islands"),
)


# Im not using here the Django User model, if login would be required we would have to create models in a different
# way by extending the User model => you can see the fotoPX application (github) as reference
# client_name, email, phone, suburb are required, the other fields are optional
# I assume that Client name is some company name, contact name is a person within the company

class Client(models.Model):
    client_name = models.CharField(max_length=128, unique=True, null=False, blank=False)
    email = models.CharField(max_length=128, null=False, blank=False)
    # phone as charfield as they may start with 0 and contain "+" etc.
    phone = models.CharField(max_length=24, null=False, blank=False)
    contact_name = models.CharField(max_length=128, null=True, blank=True)
    street = models.CharField(max_length=128, null=True, blank=True)
    # house number as CharField as numbers may contain letters and "/" etc
    house_number = models.CharField(max_length=10, null=True, blank=True)
    suburb = models.CharField(max_length=128, null=False, blank=False)
    post_code = models.PositiveSmallIntegerField(blank=True, null=True, validators=[MaxValueValidator(9999)])
    state = models.SmallIntegerField(choices=AU_STATES, null=True, blank=True)

python_test/forms.py
from django import forms
from django.forms.models import ModelForm

from python_test.models import Client


class AddClientForm(ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('client_name',)

    client_name = forms.CharField(max_length=128)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})


class SearchClientForm(forms.Form):
    SORTING = (
        (1, "Client Name"),
        (2, "Suburb"),
        (3, "Email"),
        (4, "Phone")
    )
    ORDER = (
        (1, "ASC"),
        (2, "DSC"),
    )

    client_name = forms.CharField(max_length=128, required=False,
                                  widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.CharField(max_length=128, required=False, widget=forms.TextInput(attrs={"class": "form-control"}))
    phone = forms.CharField(max_length=24, required=False, widget=forms.TextInput(attrs={"class": "form-control"}))
    suburb = forms.CharField(max_length=128, required=False, widget=forms.TextInput(attrs={"class": "form-control"}))
    sorting = forms.ChoiceField(choices=SORTING)
    order = forms.CharField(widget=forms.RadioSelect(choices=ORDER, attrs={"class": "form-check-input"}), initial=1)

python_test/views.py
from django.db.models import Q
from django.db import IntegrityError
from django.shortcuts import render
from django.views import View
from python_test.forms import AddClientForm, SearchClientForm

from python_test.models import Client


class MainPage(View):
    def get(self, request):
        all_clients = Client.objects.all()
        ctx = {"all_clients": all_clients}
        return render(request, "main_page.html", ctx)


class ShowClientDetails(View):
    def get(self, request, id):
        client = Client.objects.get(pk=id)
        ctx = {"client": client}
        return render(request, "show_user_details.html", ctx)


class AddClient(View):
    def get(self, request):
        form = AddClientForm()
        ctx = {"form": form}
        return render(request, "add_new_client.html", ctx)

    def post(self, request):
        form = AddClientForm(request.POST)
        if form.is_valid():
            client_name = form.cleaned_data["client_name"]
            email = form.cleaned_data["email"]
            phone = form.cleaned_data["phone"]
            contact_name = form.cleaned_data["contact_name"]
            street = form.cleaned_data["street"]
            house_number = form.cleaned_data["house_number"]
            suburb = form.cleaned_data["suburb"]
            post_code = form.cleaned_data["post_code"]
            state = form.cleaned_data["state"]
            try:
                Client.objects.create(
                    client_name=client_name,
                    email=email,
                    phone=phone,
                    contact_name=contact_name,
                    street=street,
                    house_number=house_number,
                    suburb=suburb,
                    post_code=post_code,
                    state=state
                )
            except IntegrityError:
                ctx = {"form": form, "error": "This client name already exists in the database!"}
                return render(request, "add_new_client.html", ctx)

            msg = "New Client Created!"
            ctx = {"form": form, "msg": msg}
            return render(request, "add_new_client.html", ctx)
        else:
            ctx = {"form": form}
        return render(request, "add_new_client.html", ctx)


class ModifyClient(View):
    def get(self, request, id):
        client_to_modify = Client.objects.get(pk=id)
        form = AddClientForm(initial={"client_name": client_to_modify.client_name,
                                      "email": client_to_modify.email,
                                      "phone": client_to_modify.phone,
                                      "contact_name": client_to_modify.contact_name,
                                      "street": client_to_modify.street,
                                      "house_number": client_to_modify.house_number,
                                      "suburb": client_to_modify.suburb,
                                      "post_code": client_to_modify.post_code,
                                      "state": client_to_modify.state,
                                      })
        ctx = {"form": form, "client": client_to_modify}
        return render(request, "modify_client.html", ctx)

    def post(self, request, id):
        form = AddClientForm(request.POST)
        client_to_modify = Client.objects.get(pk=id)
        if form.is_valid():
            client_name = form.cleaned_data["client_name"]
            email = form.cleaned_data["email"]
            phone = form.cleaned_data["phone"]
            contact_name = form.cleaned_data["contact_name"]
            street = form.cleaned_data["street"]
            house_number = form.cleaned_data["house_number"]
            suburb = form.cleaned_data["suburb"]
            post_code = form.cleaned_data["post_code"]
            state = form.cleaned_data["state"]
            try:
                Client.objects.filter(pk=id).update(
                    client_name=client_name,
                    email=email,
                    phone=phone,
                    contact_name=contact_name,
                    street=street,
                    house_number=house_number,
                    suburb=suburb,
                    post_code=post_code,
                    state=state,
                )
            except IntegrityError:
                ctx = {"form": form, "client": client_to_modify,
                       "error": "This client name already exists in the database!"}
                return render(request, "modify_client.html", ctx)

            msg = "Data Modified!!"
            ctx = {"msg": msg, "client": client_to_modify}
            return render(request, "modify_client.html", ctx)
        else:
            ctx = {"form": form, "client": client_to_modify}
            return render(request, "modify_client.html", ctx)


class DeleteClient(View):
    def get(self, request, id):
        client_to_delete = Client.objects.get(pk=id)
        client_to_delete.delete()
        ctx = {"msg": " Client Deleted!"}
        return render(request, "standard_msg_page.html", ctx)


class SearchClient(View):
    def get(self, request):
        form = SearchClientForm()
        ctx = {"form": form}
        return render(request, "search_client.html", ctx)

    def post(self, request):
        form = SearchClientForm(request.POST)
        if form.is_valid():
            client_name = form.cleaned_data["client_name"]
            email = form.cleaned_data["email"]
            phone = form.cleaned_data["phone"]
            suburb = form.cleaned_data["suburb"]
            sorting = int(form.cleaned_data["sorting"])
            order = int(form.cleaned_data["order"])

            if sorting == 1 and order == 1:
                sort_order = 'client_name'
            elif sorting == 1 and order == 2:
                sort_order = '-client_name'
            elif sorting == 2 and order == 1:
                sort_order = 'suburb'
            elif sorting == 2 and order == 2:
                sort_order = '-suburb'
            elif sorting == 3 and order == 1:
                sort_order = 'email'
            elif sorting == 3 and order == 2:
                sort_order = '-email'
            elif sorting == 4 and order == 1:
                sort_order = 'phone'
            elif sorting == 4 and order == 2:
                sort_order = '-phone'
            else:
                sort_order = 'id'

            results = Client.objects.filter(
                Q(client_name__contains=client_name) & Q(email__contains=email) &
                Q(phone__contains=phone) & Q(suburb__contains=suburb)).order_by(sort_order)

            ctx = {"form": form, "reults": results}
            return render(request, "search_client.html", ctx)
        else:
            ctx = {"form": form}
            return render(request, "search_client.html", ctx)

python_test/templates/add_new_client.html
{% include  "header.html" %}

{% if msg %}
    <div class="msgInfo">{{ msg }}</div>
{% else %}
    <h3 class="h3 h3Colors">Add New Client:</h3>
    <div>
        <form action="/add/" method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.client_name.id_for_label }}">Client Name</label>
                {{ form.client_name }}
                {{ form.client_name.errors }}
                {% if error %}
                    <ul class="errorlist">
                        <li>
                            {{ error }} </li>
                    </ul>
                {% endif %}
                <label for="{{ form.email.id_for_label }}">Client Email</label>
                {{ form.email }}
                {{ form.email.errors }}
                <label for="{{ form.phone.id_for_label }}">Phone</label>
                {{ form.phone }}
                {{ form.phone.errors }}
                <label for="{{ form.contact_name.id_for_label }}">Contact Name</label>
                {{ form.contact_name }}
                {{ form.contact_name.errors }}
                <label for="{{ form.street.id_for_label }}">Street</label>
                {{ form.street }}
                {{ form.street.errors }}
                <label for="{{ form.house_number.id_for_label }}">House Number</label>
                {{ form.house_number }}
                {{ form.house_number.errors }}
                <label for="{{ form.suburb.id_for_label }}">Suburb</label>
                {{ form.suburb }}
                {{ form.suburb.errors }}
                <label for="{{ form.post_code.id_for_label }}">Post Code</label>
                {{ form.post_code }}
                {{ form.post_code.errors }}
                <label for="{{ form.state.id_for_label }}">State</label>
                {{ form.state }}
                {{ form.state.errors }}
                <br><br>
                <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>

{% endif %}
{% include "footer.html" %}

python_test/templates/footer.html
<!-- footer start -->
</div>
</body>
</html>

python_test/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    {#link to Bootstrap files#}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>

    <script src="{% static 'js/scripts.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <title>WebIT Django Test</title>
</head>
<body>
<div class="websiteHeader">
    <nav class="navbar navbar-expand-lg navbar-dark headerRooms">
        <a class="navbar-brand" id="logo">WebIT Test</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/">Home</a>
                <a class="nav-item nav-link" href="/add">Add Client</a>
                <a class="nav-item nav-link" href="/search">Search</a>
            </div>
        </div>
    </nav>

</div>
<div class="mainContainer">
    <!-- end of header -->

python_test/templates/main_page.html
{% include  "header.html" %}
{% if msg %}

{% else %}

<h3 class="h3 h3Colors">All Clients:</h3>
<table class="table">
    <thead class="thead-light">
    <tr>
        <th scope="col" class="centerTableCol col5">ID</th>
        <th scope="col" class="centerTableCol">Client Name</th>
        <th scope="col" class="centerTableCol">Email</th>
        <th scope="col" class="centerTableCol">Phone</th>
        <th scope="col" class="centerTableCol">Suburb</th>
        <th scope="col" class="centerTableCol">State</th>
        <th scope="col" class="centerTableCol col10">(modify)</th>
        <th scope="col" class="centerTableCol col10">(delete)</th>
    </tr>
    </thead>
    <tbody>
    {% for cl in all_clients %}
    <tr>
        <td class="centerTableCol">{{ cl.id}}</td>
        <td class="centerTableCol"><a href="/details/{{ cl.id }}">{{ cl.client_name}}</a></td>
        <td class="centerTableCol">{{ cl.email}}</td>
        <td class="centerTableCol">{{ cl.phone}}</td>
        <td class="centerTableCol">{{ cl.suburb}}</td>
        <td class="centerTableCol">{{ cl.get_state_display}}</td>
        <td class="centerTableCol">
            <a href="/modify/{{ cl.id }}">
                <button class="btn btn-warning">Modify</button>
        </td>
        <td class="centerTableCol">
            <a href="/delete/{{ cl.id }}">
                <button class="btn btn-danger">Delete!</button>
            </a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endif %}
{% include "footer.html" %}

python_test/templates/modify_client.html
{% include  "header.html" %}

{% if msg %}
    <div class="msgInfo">{{ msg }}</div>
{% else %}
    <h3 class="h3 h3Colors">Modify Client:</h3>
    <div>
        <form action="/modify/{{ client.id }}" method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.client_name.id_for_label }}">Client Name</label>
                {{ form.client_name }}
                {{ form.client_name.errors }}
                {% if error %}
                    <ul class="errorlist">
                        <li>
                            {{ error }} </li>
                    </ul>
                {% endif %}
                <label for="{{ form.email.id_for_label }}">Client Email</label>
                {{ form.email }}
                {{ form.email.errors }}
                <label for="{{ form.phone.id_for_label }}">Phone</label>
                {{ form.phone }}
                {{ form.phone.errors }}
                <label for="{{ form.contact_name.id_for_label }}">Contact Name</label>
                {{ form.contact_name }}
                {{ form.contact_name.errors }}
                <label for="{{ form.street.id_for_label }}">Street</label>
                {{ form.street }}
                {{ form.street.errors }}
                <label for="{{ form.house_number.id_for_label }}">House Number</label>
                {{ form.house_number }}
                {{ form.house_number.errors }}
                <label for="{{ form.suburb.id_for_label }}">Suburb</label>
                {{ form.suburb }}
                {{ form.suburb.errors }}
                <label for="{{ form.post_code.id_for_label }}">Post Code</label>
                {{ form.post_code }}
                {{ form.post_code.errors }}
                <label for="{{ form.state.id_for_label }}">State</label>
                {{ form.state }}
                {{ form.state.errors }}
                <br><br>
                <button type="submit" class="btn btn-primary">Modify Client</button>
        </form>
    </div>

{% endif %}
{% include "footer.html" %}

python_test/templates/search_client.html
{% include  "header.html" %}

{% if msg %}
    <div class="msgInfo">{{ msg }}</div>
{% else %}
    <h3 class="h3 h3Colors">Search for Client:</h3>
    <div>
    <form action="/search/" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.client_name.id_for_label }}">Client Name</label>
            {{ form.client_name }}
            {{ form.client_name.errors }}
            <label for="{{ form.suburb.id_for_label }}">Suburb</label>
            {{ form.suburb }}
            {{ form.suburb.errors }}
            <label for="{{ form.email.id_for_label }}">Client Email</label>
            {{ form.email }}
            {{ form.email.errors }}
            <label for="{{ form.phone.id_for_label }}">Phone</label>
            {{ form.phone }}
            {{ form.phone.errors }}
            <div class="halfcol6">
                <label for="{{ form.sorting.id_for_label }}">Sorting</label>
                {{ form.sorting }}
                <br></div>
            <div class="halfcol6">
                <label for="{{ form.order.id_for_label }}">Order</label>
                {{ form.order }}
                {{ form.order.errors }}
            </div>
            <br><br>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">SEARCH</button>
    </form>

    {% if reults %}
        <hr>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol col5">ID</th>
                <th scope="col" class="centerTableCol">Client Name</th>
                <th scope="col" class="centerTableCol">Email</th>
                <th scope="col" class="centerTableCol">Phone</th>
                <th scope="col" class="centerTableCol">Suburb</th>
                <th scope="col" class="centerTableCol">State</th>
                <th scope="col" class="centerTableCol col10">(modify)</th>
                <th scope="col" class="centerTableCol col10">(delete)</th>
            </tr>
            </thead>
            <tbody>
            {% for cl in reults %}
                <tr>
                    <td class="centerTableCol">{{ cl.id }}</td>
                    <td class="centerTableCol"><a href="/details/{{ cl.id }}">{{ cl.client_name }}</a></td>
                    <td class="centerTableCol">{{ cl.email }}</td>
                    <td class="centerTableCol">{{ cl.phone }}</td>
                    <td class="centerTableCol">{{ cl.suburb }}</td>
                    <td class="centerTableCol">{{ cl.get_state_display }}</td>
                    <td class="centerTableCol">
                        <a href="/modify/{{ cl.id }}">
                            <button class="btn btn-warning">Modify</button>
                    </td>
                    <td class="centerTableCol">
                        <a href="/delete/{{ cl.id }}">
                            <button class="btn btn-danger">Delete!</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% endif %}

{% endif %}
{% include "footer.html" %}

python_test/templates/show_user_details.html
{% include  "header.html" %}
{% if msg %}
    <div class="msgInfo">{{ msg }}</div>
{% else %}
    <h3 class="h3 h3Colors">Client: {{ client.client_name }}</h3>
    <div>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol">Label</th>
                <th scope="col" class="centerTableCol">Data</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Name</td>
                <td>{{ client.client_name }}</td>
            </tr>
            <tr>
                <td>email</td>
                <td>{{ client.email }}</td>
            </tr>
            <tr>
                <td>Phone</td>
                <td>{{ client.phone }}</td>
            </tr>
            <tr>
                <td>Contact Name</td>
                <td>{{ client.contact_name }}</td>
            </tr>
            <tr>
                <td>Street</td>
                <td>{{ client.street }}</td>
            </tr>
            <tr>
                <td>House Number</td>
                <td>{{ client.house_number }}</td>
            </tr>
            <tr>
                <td>Suburb</td>
                <td>{{ client.suburb }}</td>
            </tr>
            <tr>
                <td>Post Code</td>
                <td>{{ client.post_code }}</td>
            </tr>
            <tr>
                <td>State</td>
                <td>{{ client.get_state_display}}</td>
            </tr>
            </tbody>
        </table>
    </div>

    <hr>
    <a href="/modify/{{ client.id }}">
        <button type="submit" class="btn btn-warning">Modify</button>
    </a>
    <a href="/delete/{{ client.id }}">
        <button class="btn btn-danger">Delete</button>
    </a>
{% endif %}
{% include "footer.html" %}

python_test/templates/standard_msg_page.html
{% include  "header.html" %}

{% if msg %}
    <div class="msgInfo">{{ msg }}</div>
{% else %}


{% endif %}
{% include "footer.html" %}